-- create a table
CREATE TABLE CLASSE(
  NOME TEXT NOT NULL,
  TURMA TEXT NOT NULL,
  IDADE INTEGER PRIMARY KEY,
  BAIRRO TEXT NOT NULL,

);
-- insert some values
INSERT INTO CLASSE VALUES ('ANA','2° DS,12,'BURACO DA SALA');
INSERT INTO CLASSE VALUES ('MATHEUS','2° DS,12,'PERTO DA PORTA');
INSERT INTO CLASSE VALUES ('MURILO', 'BICICLETARIA','13''2°DS');
INSERT INTO CLASSE VALUES ('JOÃO','BAIXADA','2°DS');
INSERT INTO CLASSE VALUES (2, 'Joanna', 'F');
INSERT INTO CLASSE VALUES (2, 'Joanna', 'F');
INSERT INTO CLASSE VALUES (2, 'Joanna', 'F');
INSERT INTO CLASSE VALUES (2, 'Joanna', 'F');
INSERT INTO CLASSE VALUES (2, 'Joanna', 'F');
INSERT INTO CLASSE VALUES (2, 'Joanna', 'F');
INSERT INTO CLASSE VALUES (2, 'Joanna', 'F');
INSERT INTO CLASSE VALUES (2, 'Joanna', 'F');

-- fetch some values
SELECT * FROM CLASSE WHERE WHERE IDADE 
SELECT * FROM CLASSE WHERE WHERE BAIRRO
SELECT * FROM CLASSE WHERE WHERE TURMA
SELECT * FROM CLASSE WHERE WHERE IDADE 